<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
	</PropertyGroup>

	<!-- References -->
	<ItemGroup>
		<Compile Include="TerrariaArcRaiders.cs" />
		<Compile Include="Core\**\*.cs" />
		<Compile Include="Adapters\**\*.cs" />
		<Compile Include="Tests\Unit\**\*.cs" />
	</ItemGroup>

</Project>